### ISSUE TITLE
BPM = 0 makes division by 0... (yes, there're charts with 0 as bpm...)

### ISSUE THREAD

**Issue by AntogamerYT** [Corne2Plum3/fnf2osumania#10]
**Describe the bug**
The app gives me an error while converting Defeat Hard from Vs Impostor V3

**Error message**
Traceback (most recent call last):
  File "fnf_converter.py", line 535, in exportAsOsz
  File "fnf_converter.py", line 154, in exportOsuFile
  File "fnf_converter.py", line 342, in optimizeBPMList
  File "fnf_converter.py", line 599, in bpmToMs
ZeroDivisionError: division by zero

**Screenshots:**
![image](https://user-images.githubusercontent.com/64664639/139541427-16325d8a-f55b-444b-8f11-f999f0ea9871.png)

**Program version:**
1.1.3

**Plateform:**
Windows 11, .exe version

**Used files:**
[Files.zip](https://github.com/Corne2Plum3/fnf2osumania/files/7447120/Files.zip)

**Additional context:**
Nothing else, btw thanks for fixing #9

**Comment by Corne2Plum3** [comment]
Holy sh*t why are you playing the mods with the worsts charts files!?

No seriously I think there is somewhere in your chart file where the bpm is 0 and the program wasn't ready for that. I'm not sure about that but I'll check this as soon as possible

**Comment by Corne2Plum3** [comment]
@AntogamerYT For your map check 'Unique BPM', it works with this option checked.

**Comment by Corne2Plum3** [comment]
Fixed with 1.1.4 update.

Also you should install the font Barlow Condesnsed, that why the content of the window is cropped...
