### ISSUE TITLE
add the abitty to convert charts with more keys into to osu!mania

### ISSUE THREAD

**Issue by MASE19SEC** [Corne2Plum3/fnf2osumania#16]
i cant convert god eater into osu!mania

make so you can convert fnf charts with more than 4 keys

also add so both sides can be converted into the amount of keys the chart uses for each sid

**Comment by Marcos875433** [comment]
[fnf2osumania](https://github.com/Marcos875433/fnf2osumania/releases/download/v1.1.4S/fnf2osumania.zip) I made a fork, it has 4K to 9K support for each player
