### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Play Animation'

### ISSUE THREAD

**Issue by DreckDreemurr** [Corne2Plum3/fnf2osumania#19]
This has always been appearing when I try to export any song from this mod. Its the Pibby mod btw.

![Github](https://user-images.githubusercontent.com/97374419/148669492-2a269c18-0004-46c8-899b-174a8801b6ad.png)

Program version
Version 1.1.4

OS
Windows 10

**Comment by Corne2Plum3** [comment]
Which mod?

**Comment by DreckDreemurr** [comment]
> Which mod?

Its https://gamebanana.com/mods/download/344757 this mod

**Comment by dothenotive** [comment]
Closed, read #20

**Comment by Corne2Plum3** [comment]
Should be fixed with the 1.1.6 update. You should try with this version and create a new issue if it's not fixed.
