### ISSUE TITLE
Buttons Getting Cut Off

### ISSUE THREAD

**Issue by Desati123** [Corne2Plum3/fnf2osumania#2]
**Describe the bug**
After installing all the prerequisites, the program opens and functions fine but I'm unable to export anything due to the right side getting chopped off. It might be important to note I am using a 2k monitor, although after changing my resolution to 1080p, it didn't seem to fix the issue. It could also be that I have a custom scale set on windows (135%) that might be the cause. If it turns out to be the windows global scaling to be that issue I'd like to not have to change that back to the default.

    **Screenshots**
![Window](https://user-images.githubusercontent.com/53101674/135729840-26de60b9-050f-4751-a575-47682ae6ffaa.PNG)
Can't set the background image so It gives me an error when I try to export
        
    **OS and version:**
Windows 10
Vers. 1.1 (Latest)

    **ty for taking the time to read**
<3

**Comment by Desati123** [comment]
**Update**
![anotha](https://user-images.githubusercontent.com/53101674/135730472-9f081af7-392c-414a-abab-0b2454753a04.PNG)
I just swapped the scaling back to its default and it wasn't fixed, not sure what's going on then sorry.

**Comment by Corne2Plum3** [comment]
It's weird because you don't have the custom font to fix this issue 🤔 
Maybe I should allow window resize if the font doesn't load...

**Comment by Corne2Plum3** [comment]
Ah I just remember but I forgot to say it but you have to install this font, so it would work: https://fonts.google.com/specimen/Barlow+Condensed

**Comment by Desati123** [comment]
Yep the font fixed the issue, I think I'm gonna close it with that

tyvm
