### ISSUE TITLE
.osz Process Crashes Mid Download

### ISSUE THREAD

**Issue by EatitKid** [Corne2Plum3/fnf2osumania#24]
I did everything correctly, filled everything as needed, and the .osz crashes saying I did something wrong.

**Error Message:**
Traceback (most recent call last):
  File "fnf_converter.py", line 553, in exportAsOsz
  File "fnf_converter.py", line 172, in exportOsuFile
  File "fnf_converter.py", line 305, in getNotesPlayer
ValueError: invalid literal for int() with base 10: 'Add Camera Zoom'

**Screenshot:**
![Screenshot (236)](https://user-images.githubusercontent.com/104241267/164867001-6a7e9f0c-0edf-4d00-85d9-eb02c354dc83.png)

**Program version:**
1.1.5

**Platform:**
Windows 11

I opened the "main.exe" file, so I assume .exe

**Used files:**
N/A

**Additional context:**
Help I'm not smart enough

**Comment by Corne2Plum3** [comment]
Seems similar to #19 but I'm not sure, that's why I keep the issue open for now.

**Comment by Corne2Plum3** [comment]
After working on the code, this is the same bug as described as #19, which should be fixed with the 1.1.6 update.
