### ISSUE TITLE
error on export

### ISSUE THREAD

**Issue by thiagoabreutnb** [Corne2Plum3/fnf2osumania#25]
**Describe the bug**
when i complete every thing and i export the osz it causes an errror when it reaches 55%.

**Error message**
Traceback (most recent call last):
  File "fnf_converter.py", line 559, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 809, in export
  File "site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
PermissionError: [Errno 13] Permission denied: 'output/me - MILF/audio.mp3'

**Screenshots:**
![image](https://user-images.githubusercontent.com/93147849/168140649-28d25df4-930c-4376-a9b4-1f917a326d82.png)
.

**Program version:**
1.1.6*

**Plateform:**
windows 10*

i have phyton and the version is 3.10*

**Used files:**
If you input files in this program, post them here (just drag the files in this box), it would be useful to understand how the bug happened.

**Additional context:**
Something to add?

**Comment by Corne2Plum3** [comment]
Seems you don't have writing permissions where you put the converter.
1. Try to move the converter's folder in another location then run it.
2. Check the folder where's the converter by using Right Click -> Properties and be sure that you have modifications and deletions permissions.

**Comment by thiagoabreutnb** [comment]
hmmm let me try

**Comment by thiagoabreutnb** [comment]
workeed thx
