### ISSUE TITLE
Some keys get doubled.

### ISSUE THREAD

**Issue by ZedDevStuff** [Corne2Plum3/fnf2osumania#27]
**Describe the bug**
On some songs i converted, some keys got duplicated at the same place making it that even if i hit them, i miss.

**Program version:**
1.1.6

**Plateform:**
Windows 7, exe with python 3.8.10

Also, please specify what did you used exactly *(the .exe file or the source code?)*. If you used Python, please specify the version of your Python *(example: Python 3.7.6)*

**Additional context:**
I haven't had this issue with 1.1.5 but that may be because i haven't used it a lot. Might also be a problem with the chart.

**Comment by Corne2Plum3** [comment]
If you used the map type to "[4K] Players 1 and 2" this is a known issue.

Would be nice if you could provide more details so I can recreate the bug:
- The song and the fnf mod you used.
- The difficulties you created, especially their **map type** (4K, 8K, ...)

**Comment by ZedDevStuff** [comment]
> If you used the map type "[4K] Players 1 and 2" this is a known issue.
> 
> Would be nice if you could provide more details so I can recreate the bug:
> - The song and the fnf mod you used.
> - The difficulties you created, especially their **map type** (4K, 8K, ...)

Tricky v2 (directly took the files from the github repo) on Hellclown and Madness on normal and hard. I played in Easy without issues, also i remembered that Notepad++ can remove duplicate lines in a file so i used that on them a few days ago

**Comment by ZedDevStuff** [comment]
> If you used the map type "[4K] Players 1 and 2" this is a known issue.
> 
> Would be nice if you could provide more details so I can recreate the bug:
> - The song and the fnf mod you used.
> - The difficulties you created, especially their **map type** (4K, 8K, ...)

Tricky v2 (directly took the files from the github repo) on Hellclown and Madness on normal and hard. I played in Easy without issues, also i remembered that Notepad++ can remove duplicate lines in a file so i used that on them a few days ago

**Comment by Corne2Plum3** [comment]
Fixed in #31
