### ISSUE TITLE
When clicking on the link to find the download for the converter it leads to a 404.

### ISSUE THREAD

**Issue by Striker201010** [Corne2Plum3/fnf2osumania#36]
**Bug description**
When clicking on the link to download the latest version "[https://github.com/Corne2Plum3/fnf2osumania/blob/main/here](https://github.com/Corne2Plum3/fnf2osumania/blob/main/here)" it leads to a 404 page. Where do I download the converter?

**Error message**
404 - page not found
The main branch of **fnf2osumania** does not contain the path here.

**Screenshots:**
![image](https://github.com/Corne2Plum3/fnf2osumania/assets/131113824/12ec9981-e040-4364-81e7-7f92a07429d9)

**Program version:**
N/A

**_Plate_form:**
Windows 10

Also, please specify what did you used exactly *(the .exe file or the source code?)*. If you used Python, please specify the version of your Python *(example: Python 3.7.6)*
The thing is I **can't** find the .exe file.

**Used files:**
If you input files in this program, post them here (just drag the files in this box), it would be useful to reproduce the bug.
If it's a mod, say what mod is it and please provide a download link.
N/A

**Additional context:**
Any additional comments?
Yes, what Python version is recommended?

**Comment by Corne2Plum3** [comment]
Correct link is https://github.com/Corne2Plum3/fnf2osumania/releases

Where you found that link with "here" on it?

**Comment by Striker201010** [comment]
Oh, when clicking on the link it leads to "[https://github.com/Corne2Plum3/fnf2osumania/blob/main/here](https://github.com/Corne2Plum3/fnf2osumania/blob/main/here)" but copy and pasting what the url says leads to [https://github.com/Corne2Plum3/fnf2osumania/releases](https://github.com/Corne2Plum3/fnf2osumania/blob/main/here).

**Comment by Corne2Plum3** [comment]
Fixed in 8e41076e884ccf31689891e31eb1b2ccbc8a3219, thanks for your report
