### ISSUE TITLE
5-key overlaps

### ISSUE THREAD

**Issue by Shizuru1** [Corne2Plum3/fnf2osumania#37]
**Describe the bug**
In 5 key format, all the notes in the 1st and 2nd lanes get put onto the 1st lane, and the subsequent lanes move down as well, leaving the 5th lane completely empty, and the 1st lane crowded with overlaps.

**Program version:**
1.3.2

**Platform:**
Windows 11

Also, please specify what did you used exactly *(the .exe file or the source code?)*. 
Both did the same thing. Python 3.13.1

**Used files:**
[death-toll-hard.json](https://github.com/user-attachments/files/18150865/death-toll-hard.json)
[death-toll-hell.json](https://github.com/user-attachments/files/18151099/death-toll-hell.json)

**Comment by Shizuru1** [comment]
May be to do with having different difficulties with different amounts of keys. I had two with 4 key and two with 5 key.

**Comment by Shizuru1** [comment]
![image](https://github.com/user-attachments/assets/3fc3c075-ea6b-48c6-974e-f0739ff84e4b)
I fixed it. just use ceil() instead of int() when generating the osu file. Because int rounds down sometimes, and the float already just barely reaches the next column, so rounding down means a few columns will be mistaken as earlier columns. As far as I can tell, doesn't cause any other bugs.

**Comment by Corne2Plum3** [comment]
@Shizuru1 If you changed the code to solve the problem you can make a pull request

**Comment by Corne2Plum3** [comment]
Solved by #39.

**Comment by Corne2Plum3** [comment]
Released version 1.3.3 that should fix your problem
