### ISSUE TITLE
Can't export .osz file on a (specific) mod song

### ISSUE THREAD

**Issue by Zoter47** [Corne2Plum3/fnf2osumania#5]
**Describe the bug**
The .osz file couldn't be created because it couldn't find the files

**Error message**
Traceback (most recent call last):
  File "fnf_converter.py", line 506, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 685, in from_file
  File "site-packages\pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Screenshots**
![image](https://user-images.githubusercontent.com/91847315/136457909-1565aacf-234f-4fd9-8e28-b9987bd2d839.png)

**OS and version:**
Windows 10 21H1 (OS Build 19043.1266)

**Used files:**

Audio file 1: 
Inst.ogg (Can't add .ogg because of github)

Audio file 2:
Voices.ogg (Can't add .ogg because of github)

Difficulty Easy file ([4k] Player 1 (Boyfriend), [4k] Players 1 and 2, [8k] 2 Players):
megalo strike back-easy.json (Can't add .json because of github)

Difficulty Normal file ([4k] Player 1 (Boyfriend), [4k] Players 1 and 2, [8k] 2 Players):
megalo strike back.json (Can't add .json because of github)

Difficulty Hard file ([4k] Player 1 (Boyfriend), [4k] Players 1 and 2, [8k] 2 Players):
megalo strike back-hard.json (Can't add .json because of github)

Background:
![chara-menu](https://user-images.githubusercontent.com/91847315/136460361-dad4662d-d4f3-4351-bb43-3d73be3ca5e3.jpg)

**Additional context**
I like that something like this exists and I hope this gets more popular!

**Comment by Zoter47** [comment]
Yes. Does this work?
![Screenshot 2021-10-09 171954](https://user-images.githubusercontent.com/91847315/136664325-339d7aaf-5caf-4a11-b890-73209dc8a719.png)

**Comment by Corne2Plum3** [comment]
Yeah it happens when you don't have ffmpeg. So install it like said @Marcos875433, start the program again and it should work.
