### ISSUE TITLE
I can't hit the notes of a song

### ISSUE THREAD

**Issue by AntogamerYT** [Corne2Plum3/fnf2osumania#9]
**Describe the bug**
When playing a song that I converted (Blocked by the Vs Dave mod) only the first notes are hittable for a strange reason..

**Error message**
No error message

**Screenshots:**
I will attach a video if I can
Update: no, I can't sorry, my pc lags af when trying to record

**Program version:**
v1.1.2

**Platform:**
Windows 11

.exe file

**Used files:**
[Files.zip](https://github.com/Corne2Plum3/fnf2osumania/files/7444823/Files.zip)

**Additional context:**

**Comment by Corne2Plum3** [comment]
Never seen notes likes this, that why the program tries to make long notes with negative length instead of normal notes.

```
[
  86799.0,
  4.0,
  -86799.0
],
```

To fix, I'll consider that when you have a negative value as the 3rd argument of a note (supposed to be the length of the note), I'll consider it as a normal note (length = 0)

**Comment by Corne2Plum3** [comment]
Fixed with 1.1.3 release.
